#!/bin/bash
#usage: acc <mode> <file> <aspell options>
#requires: aspell
if [ $# -lt 2 ];
then
echo "Usage:                ./acc.sh <mode> \"<file>\" \"(<aspell options>)\"";
echo "<mode>:               a mode file, typically ending in .pl";
echo "<file>:               the file you wish to check, or a file-ending specified by \"*.ext\"";
echo "<aspell options>:     options that are passed directly to aspell, in double quotes";
exit $EINVAL
fi
mode=$1
files=$2
opts=$3
for datei in $(find -name "$files")
do
    errs=`cat $datei | perl $mode | aspell $opts list`
    [ ! -z "$errs" ] && echo "======$datei====="
    for i in $errs
    do
    echo $i;
    done
done
