#!/bin/bash
#usage: acc <mode> <file> <aspell options>
#requires: aspell
if [ $# -lt 2 ];
then
echo "Usage: ./acc.sh <mode> <file> (<aspell options>)"
exit $EINVAL
fi

errs=`cat $2 | perl $1 | aspell $3 list`
[ ! -z "$errs" ] && echo "====== $2 ====="

for i in $errs
do
echo $i;

done
